# Generated by Django 5.1.2 on 2025-10-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_billgroup_expense_expensesplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='ai_generated_data',
            field=models.JSONField(blank=True, help_text='Complete AI-generated itinerary JSON from Gemini API', null=True),
        ),
    ]
